using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Events;
public class foot : MonoBehaviour
{
      //Ú’n‚µ‚½ê‡‚Ìˆ—
    public UnityEvent OnEnterGround;
    //’n–Ê‚©‚ç—£‚ê‚½ê‡‚Ìˆ—
    public UnityEvent OnExitGround;
    //Ú’n”
    private int enterNum = 0;

    private void OnTriggerEnter(Collider collision)
    {
        Debug.Log("OnGround!");
        enterNum++;
        OnEnterGround.Invoke();
    }

    private void OnTriggerExit(Collider collision)
    {
        Debug.Log("ExitGround!");
        enterNum--;
        if (enterNum <= 0) {
            OnExitGround.Invoke();
        }
    }
}
